import { find, flow, map, orderBy, values, pick } from 'lodash/fp'
import { Country } from '@app/graphql'
import { IOption } from '@components/FormElements/Form'

export interface ICountry {
  name: string
  iso3: string
  code: string
}

export const COUNTRIES_MAP: ICountry[] = [
  { name: 'Afghanistan', iso3: 'AFG', code: '004' },
  { name: 'Åland Islands', iso3: 'ALA', code: '248' },
  { name: 'Albania', iso3: 'ALB', code: '008' },
  { name: 'Algeria', iso3: 'DZA', code: '012' },
  { name: 'American Samoa', iso3: 'ASM', code: '016' },
  { name: 'Andorra', iso3: 'AND', code: '020' },
  { name: 'Angola', iso3: 'AGO', code: '024' },
  { name: 'Anguilla', iso3: 'AIA', code: '660' },
  { name: 'Antarctica', iso3: 'ATA', code: '010' },
  { name: 'Antigua and Barbuda', iso3: 'ATG', code: '028' },
  { name: 'Argentina', iso3: 'ARG', code: '032' },
  { name: 'Armenia', iso3: 'ARM', code: '051' },
  { name: 'Aruba', iso3: 'ABW', code: '533' },
  { name: 'Australia', iso3: 'AUS', code: '036' },
  { name: 'Austria', iso3: 'AUT', code: '040' },
  { name: 'Azerbaijan', iso3: 'AZE', code: '031' },
  { name: 'Bahamas', iso3: 'BHS', code: '044' },
  { name: 'Bahrain', iso3: 'BHR', code: '048' },
  { name: 'Bangladesh', iso3: 'BGD', code: '050' },
  { name: 'Barbados', iso3: 'BRB', code: '052' },
  { name: 'Belarus', iso3: 'BLR', code: '112' },
  { name: 'Belgium', iso3: 'BEL', code: '056' },
  { name: 'Belize', iso3: 'BLZ', code: '084' },
  { name: 'Benin', iso3: 'BEN', code: '204' },
  { name: 'Bermuda', iso3: 'BMU', code: '060' },
  { name: 'Bhutan', iso3: 'BTN', code: '064' },
  { name: 'Bolivia (Plurinational State of)', iso3: 'BOL', code: '068' },
  { name: 'Bonaire, Sint Eustatius and Saba', iso3: 'BES', code: '535' },
  { name: 'Bosnia and Herzegovina', iso3: 'BIH', code: '070' },
  { name: 'Botswana', iso3: 'BWA', code: '072' },
  { name: 'Bouvet Island', iso3: 'BVT', code: '074' },
  { name: 'Brazil', iso3: 'BRA', code: '076' },
  { name: 'British Indian Ocean Territory', iso3: 'IOT', code: '086' },
  { name: 'Brunei Darussalam', iso3: 'BRN', code: '096' },
  { name: 'Bulgaria', iso3: 'BGR', code: '100' },
  { name: 'Burkina Faso', iso3: 'BFA', code: '854' },
  { name: 'Burundi', iso3: 'BDI', code: '108' },
  { name: 'Cabo Verde', iso3: 'CPV', code: '132' },
  { name: 'Cambodia', iso3: 'KHM', code: '116' },
  { name: 'Cameroon', iso3: 'CMR', code: '120' },
  { name: 'Canada', iso3: 'CAN', code: '124' },
  { name: 'Cayman Islands', iso3: 'CYM', code: '136' },
  { name: 'Central African Republic', iso3: 'CAF', code: '140' },
  { name: 'Chad', iso3: 'TCD', code: '148' },
  { name: 'Chile', iso3: 'CHL', code: '152' },
  { name: 'China', iso3: 'CHN', code: '156' },
  { name: 'Christmas Island', iso3: 'CXR', code: '162' },
  { name: 'Cocos (Keeling) Islands', iso3: 'CCK', code: '166' },
  { name: 'Colombia', iso3: 'COL', code: '170' },
  { name: 'Comoros', iso3: 'COM', code: '174' },
  { name: 'Congo', iso3: 'COG', code: '178' },
  { name: 'Congo, Democratic Republic of the', iso3: 'COD', code: '180' },
  { name: 'Cook Islands', iso3: 'COK', code: '184' },
  { name: 'Costa Rica', iso3: 'CRI', code: '188' },
  { name: "Côte d'Ivoire", iso3: 'CIV', code: '384' },
  { name: 'Croatia', iso3: 'HRV', code: '191' },
  { name: 'Cuba', iso3: 'CUB', code: '192' },
  { name: 'Curaçao', iso3: 'CUW', code: '531' },
  { name: 'Cyprus', iso3: 'CYP', code: '196' },
  { name: 'Czechia', iso3: 'CZE', code: '203' },
  { name: 'Denmark', iso3: 'DNK', code: '208' },
  { name: 'Djibouti', iso3: 'DJI', code: '262' },
  { name: 'Dominica', iso3: 'DMA', code: '212' },
  { name: 'Dominican Republic', iso3: 'DOM', code: '214' },
  { name: 'Ecuador', iso3: 'ECU', code: '218' },
  { name: 'Egypt', iso3: 'EGY', code: '818' },
  { name: 'El Salvador', iso3: 'SLV', code: '222' },
  { name: 'Equatorial Guinea', iso3: 'GNQ', code: '226' },
  { name: 'Eritrea', iso3: 'ERI', code: '232' },
  { name: 'Estonia', iso3: 'EST', code: '233' },
  { name: 'Eswatini', iso3: 'SWZ', code: '748' },
  { name: 'Ethiopia', iso3: 'ETH', code: '231' },
  { name: 'Falkland Islands (Malvinas)', iso3: 'FLK', code: '238' },
  { name: 'Faroe Islands', iso3: 'FRO', code: '234' },
  { name: 'Fiji', iso3: 'FJI', code: '242' },
  { name: 'Finland', iso3: 'FIN', code: '246' },
  { name: 'France', iso3: 'FRA', code: '250' },
  { name: 'French Guiana', iso3: 'GUF', code: '254' },
  { name: 'French Polynesia', iso3: 'PYF', code: '258' },
  { name: 'French Southern Territories', iso3: 'ATF', code: '260' },
  { name: 'Gabon', iso3: 'GAB', code: '266' },
  { name: 'Gambia', iso3: 'GMB', code: '270' },
  { name: 'Georgia', iso3: 'GEO', code: '268' },
  { name: 'Germany', iso3: 'DEU', code: '276' },
  { name: 'Ghana', iso3: 'GHA', code: '288' },
  { name: 'Gibraltar', iso3: 'GIB', code: '292' },
  { name: 'Greece', iso3: 'GRC', code: '300' },
  { name: 'Greenland', iso3: 'GRL', code: '304' },
  { name: 'Grenada', iso3: 'GRD', code: '308' },
  { name: 'Guadeloupe', iso3: 'GLP', code: '312' },
  { name: 'Guam', iso3: 'GUM', code: '316' },
  { name: 'Guatemala', iso3: 'GTM', code: '320' },
  { name: 'Guernsey', iso3: 'GGY', code: '831' },
  { name: 'Guinea', iso3: 'GIN', code: '324' },
  { name: 'Guinea-Bissau', iso3: 'GNB', code: '624' },
  { name: 'Guyana', iso3: 'GUY', code: '328' },
  { name: 'Haiti', iso3: 'HTI', code: '332' },
  { name: 'Heard Island and McDonald Islands', iso3: 'HMD', code: '334' },
  { name: 'Holy See', iso3: 'VAT', code: '336' },
  { name: 'Honduras', iso3: 'HND', code: '340' },
  { name: 'Hong Kong', iso3: 'HKG', code: '344' },
  { name: 'Hungary', iso3: 'HUN', code: '348' },
  { name: 'Iceland', iso3: 'ISL', code: '352' },
  { name: 'India', iso3: 'IND', code: '356' },
  { name: 'Indonesia', iso3: 'IDN', code: '360' },
  { name: 'Iran (Islamic Republic of)', iso3: 'IRN', code: '364' },
  { name: 'Iraq', iso3: 'IRQ', code: '368' },
  { name: 'Ireland', iso3: 'IRL', code: '372' },
  { name: 'Isle of Man', iso3: 'IMN', code: '833' },
  { name: 'Israel', iso3: 'ISR', code: '376' },
  { name: 'Italy', iso3: 'ITA', code: '380' },
  { name: 'Jamaica', iso3: 'JAM', code: '388' },
  { name: 'Japan', iso3: 'JPN', code: '392' },
  { name: 'Jersey', iso3: 'JEY', code: '832' },
  { name: 'Jordan', iso3: 'JOR', code: '400' },
  { name: 'Kazakhstan', iso3: 'KAZ', code: '398' },
  { name: 'Kenya', iso3: 'KEN', code: '404' },
  { name: 'Kiribati', iso3: 'KIR', code: '296' },
  { name: "Korea (Democratic People's Republic of)", iso3: 'PRK', code: '408' },
  { name: 'Korea, Republic of', iso3: 'KOR', code: '410' },
  { name: 'Kuwait', iso3: 'KWT', code: '414' },
  { name: 'Kyrgyzstan', iso3: 'KGZ', code: '417' },
  { name: "Lao People's Democratic Republic", iso3: 'LAO', code: '418' },
  { name: 'Latvia', iso3: 'LVA', code: '428' },
  { name: 'Lebanon', iso3: 'LBN', code: '422' },
  { name: 'Lesotho', iso3: 'LSO', code: '426' },
  { name: 'Liberia', iso3: 'LBR', code: '430' },
  { name: 'Libya', iso3: 'LBY', code: '434' },
  { name: 'Liechtenstein', iso3: 'LIE', code: '438' },
  { name: 'Lithuania', iso3: 'LTU', code: '440' },
  { name: 'Luxembourg', iso3: 'LUX', code: '442' },
  { name: 'Macao', iso3: 'MAC', code: '446' },
  { name: 'Madagascar', iso3: 'MDG', code: '450' },
  { name: 'Malawi', iso3: 'MWI', code: '454' },
  { name: 'Malaysia', iso3: 'MYS', code: '458' },
  { name: 'Maldives', iso3: 'MDV', code: '462' },
  { name: 'Mali', iso3: 'MLI', code: '466' },
  { name: 'Malta', iso3: 'MLT', code: '470' },
  { name: 'Marshall Islands', iso3: 'MHL', code: '584' },
  { name: 'Martinique', iso3: 'MTQ', code: '474' },
  { name: 'Mauritania', iso3: 'MRT', code: '478' },
  { name: 'Mauritius', iso3: 'MUS', code: '480' },
  { name: 'Mayotte', iso3: 'MYT', code: '175' },
  { name: 'Mexico', iso3: 'MEX', code: '484' },
  { name: 'Micronesia (Federated States of)', iso3: 'FSM', code: '583' },
  { name: 'Moldova, Republic of', iso3: 'MDA', code: '498' },
  { name: 'Monaco', iso3: 'MCO', code: '492' },
  { name: 'Mongolia', iso3: 'MNG', code: '496' },
  { name: 'Montenegro', iso3: 'MNE', code: '499' },
  { name: 'Montserrat', iso3: 'MSR', code: '500' },
  { name: 'Morocco', iso3: 'MAR', code: '504' },
  { name: 'Mozambique', iso3: 'MOZ', code: '508' },
  { name: 'Myanmar', iso3: 'MMR', code: '104' },
  { name: 'Namibia', iso3: 'NAM', code: '516' },
  { name: 'Nauru', iso3: 'NRU', code: '520' },
  { name: 'Nepal', iso3: 'NPL', code: '524' },
  { name: 'Netherlands', iso3: 'NLD', code: '528' },
  { name: 'New Caledonia', iso3: 'NCL', code: '540' },
  { name: 'New Zealand', iso3: 'NZL', code: '554' },
  { name: 'Nicaragua', iso3: 'NIC', code: '558' },
  { name: 'Niger', iso3: 'NER', code: '562' },
  { name: 'Nigeria', iso3: 'NGA', code: '566' },
  { name: 'Niue', iso3: 'NIU', code: '570' },
  { name: 'Norfolk Island', iso3: 'NFK', code: '574' },
  { name: 'North Macedonia', iso3: 'MKD', code: '807' },
  { name: 'Northern Mariana Islands', iso3: 'MNP', code: '580' },
  { name: 'Norway', iso3: 'NOR', code: '578' },
  { name: 'Oman', iso3: 'OMN', code: '512' },
  { name: 'Pakistan', iso3: 'PAK', code: '586' },
  { name: 'Palau', iso3: 'PLW', code: '585' },
  { name: 'Palestine, State of', iso3: 'PSE', code: '275' },
  { name: 'Panama', iso3: 'PAN', code: '591' },
  { name: 'Papua New Guinea', iso3: 'PNG', code: '598' },
  { name: 'Paraguay', iso3: 'PRY', code: '600' },
  { name: 'Peru', iso3: 'PER', code: '604' },
  { name: 'Philippines', iso3: 'PHL', code: '608' },
  { name: 'Pitcairn', iso3: 'PCN', code: '612' },
  { name: 'Poland', iso3: 'POL', code: '616' },
  { name: 'Portugal', iso3: 'PRT', code: '620' },
  { name: 'Puerto Rico', iso3: 'PRI', code: '630' },
  { name: 'Qatar', iso3: 'QAT', code: '634' },
  { name: 'Réunion', iso3: 'REU', code: '638' },
  { name: 'Romania', iso3: 'ROU', code: '642' },
  { name: 'Russian Federation', iso3: 'RUS', code: '643' },
  { name: 'Rwanda', iso3: 'RWA', code: '646' },
  { name: 'Saint Barthélemy', iso3: 'BLM', code: '652' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', iso3: 'SHN', code: '654' },
  { name: 'Saint Kitts and Nevis', iso3: 'KNA', code: '659' },
  { name: 'Saint Lucia', iso3: 'LCA', code: '662' },
  { name: 'Saint Martin (French part)', iso3: 'MAF', code: '663' },
  { name: 'Saint Pierre and Miquelon', iso3: 'SPM', code: '666' },
  { name: 'Saint Vincent and the Grenadines', iso3: 'VCT', code: '670' },
  { name: 'Samoa', iso3: 'WSM', code: '882' },
  { name: 'San Marino', iso3: 'SMR', code: '674' },
  { name: 'Sao Tome and Principe', iso3: 'STP', code: '678' },
  { name: 'Saudi Arabia', iso3: 'SAU', code: '682' },
  { name: 'Senegal', iso3: 'SEN', code: '686' },
  { name: 'Serbia', iso3: 'SRB', code: '688' },
  { name: 'Seychelles', iso3: 'SYC', code: '690' },
  { name: 'Sierra Leone', iso3: 'SLE', code: '694' },
  { name: 'Singapore', iso3: 'SGP', code: '702' },
  { name: 'Sint Maarten (Dutch part)', iso3: 'SXM', code: '534' },
  { name: 'Slovakia', iso3: 'SVK', code: '703' },
  { name: 'Slovenia', iso3: 'SVN', code: '705' },
  { name: 'Solomon Islands', iso3: 'SLB', code: '090' },
  { name: 'Somalia', iso3: 'SOM', code: '706' },
  { name: 'South Africa', iso3: 'ZAF', code: '710' },
  { name: 'South Georgia and the South Sandwich Islands', iso3: 'SGS', code: '239' },
  { name: 'South Sudan', iso3: 'SSD', code: '728' },
  { name: 'Spain', iso3: 'ESP', code: '724' },
  { name: 'Sri Lanka', iso3: 'LKA', code: '144' },
  { name: 'Sudan', iso3: 'SDN', code: '729' },
  { name: 'Suriname', iso3: 'SUR', code: '740' },
  { name: 'Svalbard and Jan Mayen', iso3: 'SJM', code: '744' },
  { name: 'Sweden', iso3: 'SWE', code: '752' },
  { name: 'Switzerland', iso3: 'CHE', code: '756' },
  { name: 'Syrian Arab Republic', iso3: 'SYR', code: '760' },
  { name: 'Taiwan, Province of China', iso3: 'TWN', code: '158' },
  { name: 'Tajikistan', iso3: 'TJK', code: '762' },
  { name: 'Tanzania, United Republic of', iso3: 'TZA', code: '834' },
  { name: 'Thailand', iso3: 'THA', code: '764' },
  { name: 'Timor-Leste', iso3: 'TLS', code: '626' },
  { name: 'Togo', iso3: 'TGO', code: '768' },
  { name: 'Tokelau', iso3: 'TKL', code: '772' },
  { name: 'Tonga', iso3: 'TON', code: '776' },
  { name: 'Trinidad and Tobago', iso3: 'TTO', code: '780' },
  { name: 'Tunisia', iso3: 'TUN', code: '788' },
  { name: 'Turkey', iso3: 'TUR', code: '792' },
  { name: 'Turkmenistan', iso3: 'TKM', code: '795' },
  { name: 'Turks and Caicos Islands', iso3: 'TCA', code: '796' },
  { name: 'Tuvalu', iso3: 'TUV', code: '798' },
  { name: 'Uganda', iso3: 'UGA', code: '800' },
  { name: 'Ukraine', iso3: 'UKR', code: '804' },
  { name: 'United Arab Emirates', iso3: 'ARE', code: '784' },
  { name: 'United Kingdom of Great Britain and Northern Ireland', iso3: 'GBR', code: '826' },
  { name: 'United States of America', iso3: 'USA', code: '840' },
  { name: 'United States Minor Outlying Islands', iso3: 'UMI', code: '581' },
  { name: 'Uruguay', iso3: 'URY', code: '858' },
  { name: 'Uzbekistan', iso3: 'UZB', code: '860' },
  { name: 'Vanuatu', iso3: 'VUT', code: '548' },
  { name: 'Venezuela (Bolivarian Republic of)', iso3: 'VEN', code: '862' },
  { name: 'Viet Nam', iso3: 'VNM', code: '704' },
  { name: 'Virgin Islands (British)', iso3: 'VGB', code: '092' },
  { name: 'Virgin Islands (U.S.)', iso3: 'VIR', code: '850' },
  { name: 'Wallis and Futuna', iso3: 'WLF', code: '876' },
  { name: 'Western Sahara', iso3: 'ESH', code: '732' },
  { name: 'Yemen', iso3: 'YEM', code: '887' },
  { name: 'Zambia', iso3: 'ZMB', code: '894' },
  { name: 'Zimbabwe', iso3: 'ZWE', code: '716' }
]

export const COUNTRY_OPTIONS: IOption[] = flow(
  values,
  map<Country, IOption>((value: Country) => ({ label: find<ICountry>({ iso3: value }, COUNTRIES_MAP).name, value })),
  orderBy('label', 'asc'),
  // USA should be first
  map((option: IOption, index) => ({ ...option, index: option.value === Country.USA ? -1 : index })),
  orderBy('index', 'asc'),
  map<any, IOption>(pick(['label', 'value']))
)(Country)

export const US_STATES_OPTIONS: IOption[] = [
  { label: 'Alabama', value: 'AL' },
  { label: 'Alaska', value: 'AK' },
  { label: 'American Samoa', value: 'AS' },
  { label: 'Arizona', value: 'AZ' },
  { label: 'Arkansas', value: 'AR' },
  { label: 'California', value: 'CA' },
  { label: 'Colorado', value: 'CO' },
  { label: 'Connecticut', value: 'CT' },
  { label: 'Delaware', value: 'DE' },
  { label: 'District Of Columbia', value: 'DC' },
  { label: 'Federated States Of Micronesia', value: 'FM' },
  { label: 'Florida', value: 'FL' },
  { label: 'Georgia', value: 'GA' },
  { label: 'Guam', value: 'GU' },
  { label: 'Hawaii', value: 'HI' },
  { label: 'Idaho', value: 'ID' },
  { label: 'Illinois', value: 'IL' },
  { label: 'Indiana', value: 'IN' },
  { label: 'Iowa', value: 'IA' },
  { label: 'Kansas', value: 'KS' },
  { label: 'Kentucky', value: 'KY' },
  { label: 'Louisiana', value: 'LA' },
  { label: 'Maine', value: 'ME' },
  { label: 'Marshall Islands', value: 'MH' },
  { label: 'Maryland', value: 'MD' },
  { label: 'Massachusetts', value: 'MA' },
  { label: 'Michigan', value: 'MI' },
  { label: 'Minnesota', value: 'MN' },
  { label: 'Mississippi', value: 'MS' },
  { label: 'Missouri', value: 'MO' },
  { label: 'Montana', value: 'MT' },
  { label: 'Nebraska', value: 'NE' },
  { label: 'Nevada', value: 'NV' },
  { label: 'New Hampshire', value: 'NH' },
  { label: 'New Jersey', value: 'NJ' },
  { label: 'New Mexico', value: 'NM' },
  { label: 'New York', value: 'NY' },
  { label: 'North Carolina', value: 'NC' },
  { label: 'North Dakota', value: 'ND' },
  { label: 'Northern Mariana Islands', value: 'MP' },
  { label: 'Ohio', value: 'OH' },
  { label: 'Oklahoma', value: 'OK' },
  { label: 'Oregon', value: 'OR' },
  { label: 'Palau', value: 'PW' },
  { label: 'Pennsylvania', value: 'PA' },
  { label: 'Puerto Rico', value: 'PR' },
  { label: 'Rhode Island', value: 'RI' },
  { label: 'South Carolina', value: 'SC' },
  { label: 'South Dakota', value: 'SD' },
  { label: 'Tennessee', value: 'TN' },
  { label: 'Texas', value: 'TX' },
  { label: 'Utah', value: 'UT' },
  { label: 'Vermont', value: 'VT' },
  { label: 'Virgin Islands', value: 'VI' },
  { label: 'Virginia', value: 'VA' },
  { label: 'Washington', value: 'WA' },
  { label: 'West Virginia', value: 'WV' },
  { label: 'Wisconsin', value: 'WI' },
  { label: 'Wyoming', value: 'WY' }
]
